import './globals.css'
import type { Metadata } from 'next'
import { Inter, Calistoga } from 'next/font/google'
import Header from './Header'
import { UserProvider } from './UserContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'QandA Fashion',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <Header/>
          {children}
        </UserProvider>
      </body>
    </html>
  )
}

